manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nandairjayandi
      url-base: https://github.com/nandairjayandi
    - name: m165437
      url-base: https://github.com/M165437
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: nice-view-gem 
      remote: m165437 
      revision: v0.3.0
    - name: zmk-helpers
      remote: urob
      revision: v0.3.0
    - name: zmk-behavior-dynamic-macros
      remote: nandairjayandi # from bsalex
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: v0.3

  self:
    path: config
